name: Bug Report
description: Report a bug or unexpected behaviour in adpapi
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out as much detail as possible.

  - type: input
    id: version
    attributes:
      label: adpapi version
      placeholder: e.g. 1.4.3
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: e.g. 3.12.2
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal code or steps to reproduce the issue.
      placeholder: |
        ```python
        from adpapi.client import AdpApiClient
        ...
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: What actually happened? Include the full traceback if available.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context (OS, ADP environment, etc.)
