name: Feature Request
description: Suggest a new feature or enhancement for adpapi
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea as clearly as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What problem does this feature solve? What use-case is it for?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature you'd like, including any API ideas.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any workarounds or alternative approaches?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or references.
